version: 0.2
phases:
  install:
    commands:
      - pip install boto3
  build:
    commands:
      - echo "Ejecutando actualización de registros..."
      - python modificar_registro.py
      - echo "Generando reporte para Finanzas..."
      - python exportar_aS3.py
artifacts:
  files:
    - '**/*'